n1 = input('Digite algo: ')
print('O tipo primitivo informado é', type(n1))
print('Só tem espaços ?', n1.isspace())
print('É um número ?', n1.isnumeric())
print('É alfabético ?', n1.isalpha())
print('É alfanumério ?', n1.isalnum())
print('Está em maiúculo ?', n1.isupper())
print('Está em minúsculo ?', n1.islower())
print('Está capitalizada ?', n1.istitle())
