print('='*30)
print('>>> Combinação de expressões numéricas <<<')
print('='*30)
print(f'3 + 4 * 2 = {3 + 4 * 2}')
print('=> Na expressão acima, o operador de multiplicação tem PRECEDÊNCIA\n sobre o operador de soma...')
print('='*30)
print(f'7 + 3 * 6 - 4 ** 2 = {7 + 3 * 6 - 4 ** 2}')
print('=> No exemplo acima, o operador de POTENCIAÇÃO tem PRECEDÊNCIA sobre o operador\n de subtração, assim como o de '
      'multiplicação tem PRECEDÊNCIA sobre os\n operadores de SOMA e SUBTRAÇÃO...')
print('='*30)
print(f'(3 + 4) * 2 = {(3 + 4) * 2}')
print('=> No exemplo acima, as chaves tem PRECEDÊNCIA na expressão...')
print('='*30)
print(f'(8 / 4) ** (5 - 2) = {(8 / 4) ** (5 - 2)}')
print('=> Idem...')
